"""add interaction_settings table

Revision ID: 35b7ddb18ca3
Revises: 58636d71cc27
Create Date: 2026-03-08 16:13:56.510476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35b7ddb18ca3'
down_revision: Union[str, None] = '58636d71cc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('smart_adapt_mode', sa.Boolean(), nullable=True),
    sa.Column('custom_tune', sa.Boolean(), nullable=True),
    sa.Column('word_complexity', sa.Integer(), nullable=True),
    sa.Column('speech_speed', sa.Integer(), nullable=True),
    sa.Column('new_words_per_session', sa.Integer(), nullable=True),
    sa.Column('question_frequency', sa.String(), nullable=True),
    sa.Column('topic_focus', sa.Integer(), nullable=True),
    sa.Column('command_steps', sa.Integer(), nullable=True),
    sa.Column('patience_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_settings_child_id'), 'interaction_settings', ['child_id'], unique=True)
    op.create_index(op.f('ix_interaction_settings_created_at'), 'interaction_settings', ['created_at'], unique=False)
    op.alter_column('children', 'interests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('children', 'keywords_filter',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('children', 'focus_topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.alter_column('children', 'focus_topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('children', 'keywords_filter',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('children', 'interests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_interaction_settings_created_at'), table_name='interaction_settings')
    op.drop_index(op.f('ix_interaction_settings_child_id'), table_name='interaction_settings')
    op.drop_table('interaction_settings')
    # ### end Alembic commands ###
