"""add toy telemetry fields

Revision ID: 508db203710a
Revises: e5c7ddbd4637
Create Date: 2026-03-07 17:52:03.791206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508db203710a'
down_revision: Union[str, None] = 'e5c7ddbd4637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toys', sa.Column('manufactured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('toys', sa.Column('firmware_version', sa.String(), nullable=True))
    op.add_column('toys', sa.Column('battery_level', sa.Integer(), nullable=True))
    op.add_column('toys', sa.Column('wifi_signal', sa.Integer(), nullable=True))
    op.add_column('toys', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('toys', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_toys_created_at'), 'toys', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toys_created_at'), table_name='toys')
    op.drop_column('toys', 'updated_at')
    op.drop_column('toys', 'created_at')
    op.drop_column('toys', 'wifi_signal')
    op.drop_column('toys', 'battery_level')
    op.drop_column('toys', 'firmware_version')
    op.drop_column('toys', 'manufactured_at')
    # ### end Alembic commands ###
