"""add device secret

Revision ID: 558d1807bb8c
Revises: c1efc4ec4761
Create Date: 2026-03-07 22:09:15.298824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558d1807bb8c'
down_revision: Union[str, None] = 'c1efc4ec4761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toys', sa.Column('device_secret', sa.String(), nullable=True))
    op.create_index(op.f('ix_toys_device_secret'), 'toys', ['device_secret'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toys_device_secret'), table_name='toys')
    op.drop_column('toys', 'device_secret')
    # ### end Alembic commands ###
