"""factory manufacturing metadata

Revision ID: 58636d71cc27
Revises: 558d1807bb8c
Create Date: 2026-03-08 11:31:03.501262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58636d71cc27'
down_revision: Union[str, None] = '558d1807bb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_toys_device_secret', table_name='toys')
    op.drop_column('toys', 'device_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toys', sa.Column('device_secret', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_toys_device_secret', 'toys', ['device_secret'], unique=True)
    # ### end Alembic commands ###
