"""add factory metadata

Revision ID: c1efc4ec4761
Revises: 508db203710a
Create Date: 2026-03-07 21:05:25.903865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1efc4ec4761'
down_revision: Union[str, None] = '508db203710a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toys', sa.Column('factory_batch', sa.String(), nullable=True))
    op.add_column('toys', sa.Column('hardware_revision', sa.String(), nullable=True))
    op.create_index(op.f('ix_toys_factory_batch'), 'toys', ['factory_batch'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toys_factory_batch'), table_name='toys')
    op.drop_column('toys', 'hardware_revision')
    op.drop_column('toys', 'factory_batch')
    # ### end Alembic commands ###
