"""add performance indexes and schema updates

Revision ID: e5c7ddbd4637
Revises: 1fec5d86788e
Create Date: 2026-03-06 10:55:25.558908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c7ddbd4637'
down_revision: Union[str, None] = '1fec5d86788e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_analytics_child_date', 'analytics_history', ['child_id', 'created_at'], unique=False)
    op.create_index('idx_api_key_hash_revoked', 'api_keys', ['key_hash', 'revoked'], unique=False)
    op.create_index(op.f('ix_children_is_deleted'), 'children', ['is_deleted'], unique=False)
    op.create_index('idx_conversation_child_date', 'conversations', ['child_id', 'conversation_date'], unique=False)
    op.create_index(op.f('ix_parents_name'), 'parents', ['name'], unique=False)
    op.drop_constraint('toys_factory_device_id_key', 'toys', type_='unique')
    op.drop_constraint('toys_toy_uuid_key', 'toys', type_='unique')
    op.create_index(op.f('ix_toys_active_child_id'), 'toys', ['active_child_id'], unique=False)
    op.create_index(op.f('ix_toys_factory_device_id'), 'toys', ['factory_device_id'], unique=True)
    op.create_index(op.f('ix_toys_owner_parent_id'), 'toys', ['owner_parent_id'], unique=False)
    op.create_index(op.f('ix_toys_toy_uuid'), 'toys', ['toy_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toys_toy_uuid'), table_name='toys')
    op.drop_index(op.f('ix_toys_owner_parent_id'), table_name='toys')
    op.drop_index(op.f('ix_toys_factory_device_id'), table_name='toys')
    op.drop_index(op.f('ix_toys_active_child_id'), table_name='toys')
    op.create_unique_constraint('toys_toy_uuid_key', 'toys', ['toy_uuid'])
    op.create_unique_constraint('toys_factory_device_id_key', 'toys', ['factory_device_id'])
    op.drop_index(op.f('ix_parents_name'), table_name='parents')
    op.drop_index('idx_conversation_child_date', table_name='conversations')
    op.drop_index(op.f('ix_children_is_deleted'), table_name='children')
    op.drop_index('idx_api_key_hash_revoked', table_name='api_keys')
    op.drop_index('idx_analytics_child_date', table_name='analytics_history')
    # ### end Alembic commands ###
