"""add_streak_firmware_analytics_refactor

Revision ID: e643d43f001f
Revises: 0f053932c30c
Create Date: 2026-05-20 18:55:38.485464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e643d43f001f'
down_revision: Union[str, Sequence[str], None] = '0f053932c30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmware_releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_stable', sa.Boolean(), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmware_releases_version'), 'firmware_releases', ['version'], unique=True)
    op.create_table('child_streaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_conversation_date', sa.Date(), nullable=True),
    sa.Column('streak_started_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_child_streaks_child_id'), 'child_streaks', ['child_id'], unique=True)
    op.add_column('analytics_history', sa.Column('breakdown_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('analytics_history', 'fq')
    op.drop_column('analytics_history', 'vq')
    op.drop_column('analytics_history', 'cq')
    op.drop_column('analytics_history', 'gq')
    op.drop_column('analytics_history', 'mq')
    op.drop_column('child_analytics', 'fq')
    op.drop_column('child_analytics', 'velocity')
    op.drop_column('child_analytics', 'insight_json')
    op.drop_column('child_analytics', 'confidence')
    op.drop_column('child_analytics', 'vq')
    op.drop_column('child_analytics', 'algorithm_version')
    op.drop_column('child_analytics', 'cq')
    op.drop_column('child_analytics', 'gq')
    op.drop_column('child_analytics', 'trend_percent')
    op.drop_column('child_analytics', 'mq')
    op.drop_index('idx_child_vocab_child_word', table_name='child_vocabulary_memory')
    op.drop_index('ix_child_vocabulary_memory_word', table_name='child_vocabulary_memory')
    op.create_index('idx_child_vocab_child_word_lower', 'child_vocabulary_memory', ['child_id', sa.text('lower(word)')], unique=False)
    op.create_index('idx_vocab_child_first_seen', 'child_vocabulary_memory', ['child_id', 'first_seen'], unique=False)
    op.alter_column('children', 'guardian_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('children', 'guardian_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('idx_vocab_child_first_seen', table_name='child_vocabulary_memory')
    op.drop_index('idx_child_vocab_child_word_lower', table_name='child_vocabulary_memory')
    op.create_index('ix_child_vocabulary_memory_word', 'child_vocabulary_memory', ['word'], unique=False)
    op.create_index('idx_child_vocab_child_word', 'child_vocabulary_memory', ['child_id', 'word'], unique=False)
    op.add_column('child_analytics', sa.Column('mq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('child_analytics', sa.Column('trend_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('child_analytics', sa.Column('gq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('child_analytics', sa.Column('cq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('child_analytics', sa.Column('algorithm_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('child_analytics', sa.Column('vq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('child_analytics', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('child_analytics', sa.Column('insight_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('child_analytics', sa.Column('velocity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('child_analytics', sa.Column('fq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('analytics_history', sa.Column('mq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('analytics_history', sa.Column('gq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('analytics_history', sa.Column('cq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('analytics_history', sa.Column('vq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('analytics_history', sa.Column('fq', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('analytics_history', 'breakdown_json')
    op.drop_index(op.f('ix_child_streaks_child_id'), table_name='child_streaks')
    op.drop_table('child_streaks')
    op.drop_index(op.f('ix_firmware_releases_version'), table_name='firmware_releases')
    op.drop_table('firmware_releases')
    # ### end Alembic commands ###
