name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
            cd /home/ubuntu

            if [ ! -d "boboloo-backend-interaction" ]; then
                git clone https://github.com/MohammadNazim01/boboloo-backend-interaction.git
            fi

            cd boboloo-backend-interaction

            git fetch origin
            git reset --hard origin/main

            if [ ! -f ".env" ]; then
                echo "❌ .env file missing"
                exit 1
            fi

            sudo docker stop boboloo-backend || true
            sudo docker rm boboloo-backend || true

            sudo docker build --no-cache -t boboloo-backend .

            sudo docker run -d -p 8000:8080 \
                --env-file .env \
                --name boboloo-backend \
                --restart always \
                boboloo-backend